version: '3'
services:
  cpp-server:
    build:
      context: ./decode_server
    ports:
      - "12001:5000/udp"
    container_name: cpp-server
    networks:
      custom-net:
        ipv4_address: 172.20.0.2

  node-server:
    build:
      context: ./web_server 
    ports:
      - "12000:3000"
    container_name: node-server
    depends_on:
      - cpp-server
    networks:
      custom-net:
        ipv4_address: 172.20.0.3

networks:
  custom-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
